# Generated by Django 4.2.1 on 2023-05-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.CharField(max_length=50, verbose_name='Адресс')),
                ('port', models.CharField(blank=True, max_length=10, null=True, verbose_name='Порт')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('status', models.CharField(choices=[('online', 'онлайн'), ('offline', 'не активен'), ('undefined', 'не определено')], default='undefined', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, verbose_name='Источник-устройство')),
                ('details', models.TextField(blank=True, verbose_name='Подробности')),
                ('type', models.TextField(verbose_name='Тип Уведомления')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адресс')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('photo', models.ImageField(default=False, null=True, upload_to='media/')),
                ('active', models.BooleanField(choices=[(True, 'Активен'), (False, 'Заблоктрован')], default=True, max_length=10, verbose_name='Статус активности')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='acms.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
