# Generated by Django 4.2.1 on 2023-05-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
